/* v10 bootstrap + native-dialog onboarding */
(() => {
const style=document.createElement('link');style.rel='stylesheet';style.href='v9.css?v=10';document.head.append(style);
let root=document.getElementById('onboarding');
if(root&&root.tagName!=='DIALOG'){const d=document.createElement('dialog');[...root.attributes].forEach(a=>d.setAttribute(a.name,a.value));d.innerHTML=root.innerHTML;root.replaceWith(d);root=d}
if(root){const steps=[...root.querySelectorAll('.ob-step')],dots=[...root.querySelectorAll('#obProgress i')];let step=0,obLang=(typeof data!=='undefined'&&data.prefs?.lang)||'ro';const tx={ro:{next:'Continuă →',finish:'Începe 🐾',skip:'Sari peste',need:'Scrie un nume mai întâi 🙂',ready:'Totul e gata!',sub:'Planul zilnic va fi adaptat vârstei și profilului.'},en:{next:'Continue →',finish:'Start 🐾',skip:'Skip',need:'Please enter a name first 🙂',ready:'All set!',sub:'The daily plan will adapt to age and profile.'}};
function open(){if(!root.open)root.showModal();root.classList.add('open');root.setAttribute('aria-hidden','false')}
function close(){root.classList.remove('open');root.setAttribute('aria-hidden','true');if(root.open)root.close()}
function show(n){step=Math.max(0,Math.min(steps.length-1,n));steps.forEach((x,i)=>x.classList.toggle('active',i===step));dots.forEach((x,i)=>x.classList.toggle('on',i<=step));const back=document.getElementById('obBack'),next=document.getElementById('obNext'),skip=document.getElementById('obSkip');if(back)back.style.visibility=step?'visible':'hidden';if(next)next.textContent=step===steps.length-1?tx[obLang].finish:tx[obLang].next;if(skip)skip.textContent=tx[obLang].skip;if(step===steps.length-1){const name=(document.getElementById('obName')?.value||data.profile.name||'Poodle').trim();document.getElementById('obSummaryName')&&(document.getElementById('obSummaryName').textContent=name);document.getElementById('obSummaryMeta')&&(document.getElementById('obSummaryMeta').textContent=`${document.getElementById('obBreed')?.value||'Poodle Toy'} · ${document.getElementById('obAge')?.value||3} ${obLang==='ro'?'luni':'months'}`);document.getElementById('obReadyTitle')&&(document.getElementById('obReadyTitle').textContent=tx[obLang].ready);document.getElementById('obReadySub')&&(document.getElementById('obReadySub').textContent=tx[obLang].sub)}}
function syncLang(){data.prefs.lang=obLang;save();try{applyLang()}catch{}root.querySelectorAll('[data-ob-lang]').forEach(b=>b.classList.toggle('sel',b.dataset.obLang===obLang))}
function finish(){const name=(document.getElementById('obName')?.value||data.profile.name||'').trim();if(!name){toast(tx[obLang].need);return}data.profile.name=name;const breed=document.getElementById('obBreed')?.value;if(breed)data.profile.breed=breed;const sex=document.getElementById('obSex')?.value;if(sex)data.profile.sex=sex;const age=+document.getElementById('obAge')?.value;if(age)data.profile.age=age;const w=+document.getElementById('obWeight')?.value;if(w){data.profile.weight=w;if(data.weights?.length===1)data.weights[0].weight=w}data.prefs.lang=obLang;data.prefs.onboarded=true;save();close();try{applyLang();renderAll()}catch{}}
root.querySelectorAll('[data-ob-lang]').forEach(b=>b.onclick=()=>{obLang=b.dataset.obLang;syncLang()});root.querySelectorAll('[data-name-suggest]').forEach(b=>b.onclick=()=>{const n=document.getElementById('obName');if(n)n.value=b.dataset.nameSuggest});document.getElementById('obBack')?.addEventListener('click',()=>show(step-1));document.getElementById('obNext')?.addEventListener('click',()=>{if(step===1&&!document.getElementById('obName')?.value.trim()){toast(tx[obLang].need);return}if(step===steps.length-1)return finish();show(step+1)});document.getElementById('obSkip')?.addEventListener('click',()=>{data.prefs.onboarded=true;data.prefs.lang=obLang;save();close()});document.getElementById('retakeTutorialBtn')?.addEventListener('click',()=>{open();show(0)});root.addEventListener('cancel',e=>{e.preventDefault();close()});if(!data.prefs?.onboarded){open();show(0)}}
['v9-core.js?v=10','v9-langs.js?v=10','v9-health.js?v=10','v9-training.js?v=10','v10-training-elements.js?v=10','v11-extra-training.js?v=11','v9-ux.js?v=10'].forEach(src=>{const s=document.createElement('script');s.src=src;s.async=false;document.body.append(s)});
})();