const KEY="poodleCoachCarePremiumV4";
const todayISO=()=>new Date().toISOString().slice(0,10);
const nowTime=()=>new Date().toTimeString().slice(0,5);
const uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const sameDay=(a,b)=>new Date(a).toDateString()===new Date(b).toDateString();
const fmtDate=(d,lang="ro")=>new Date(d+"T12:00:00").toLocaleDateString(lang==="ro"?"ro-RO":"en-GB",{day:"2-digit",month:"short",year:"numeric"});
const fmtShort=d=>new Date(d).toLocaleTimeString("ro-RO",{hour:"2-digit",minute:"2-digit"});
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));

const skills=[
{id:"name",icon:"👂",ro:"Numele",en:"Name",cat:"essential",min:3,xp:15},
{id:"sit",icon:"🐕",ro:"Șezi",en:"Sit",cat:"essential",min:3,xp:20},
{id:"down",icon:"⬇️",ro:"Culcat",en:"Down",cat:"essential",min:4,xp:20},
{id:"stay",icon:"✋",ro:"Stai",en:"Stay",cat:"essential",min:4,xp:25},
{id:"recall",icon:"🎯",ro:"Vino",en:"Recall",cat:"essential",min:5,xp:30},
{id:"leave",icon:"🚫",ro:"Lasă",en:"Leave it",cat:"essential",min:4,xp:25},
{id:"drop",icon:"🧸",ro:"Dă",en:"Drop",cat:"daily",min:4,xp:20},
{id:"place",icon:"🛏️",ro:"La loc",en:"Place",cat:"daily",min:5,xp:25},
{id:"heel",icon:"🦮",ro:"Lângă",en:"Heel",cat:"daily",min:5,xp:30},
{id:"wait",icon:"🚪",ro:"Așteaptă",en:"Wait",cat:"daily",min:4,xp:25},
{id:"touch",icon:"👃",ro:"Touch",en:"Touch",cat:"trick",min:3,xp:20},
{id:"paw",icon:"🐾",ro:"Dă lăbuța",en:"Paw",cat:"trick",min:3,xp:15},
{id:"spin",icon:"🌀",ro:"Rotire",en:"Spin",cat:"trick",min:3,xp:20},
{id:"paws",icon:"🦶",ro:"Manipulare lăbuțe",en:"Paw handling",cat:"grooming",min:3,xp:20},
{id:"brush",icon:"🪮",ro:"Periaj calm",en:"Calm brushing",cat:"grooming",min:4,xp:25},
{id:"dryer",icon:"💨",ro:"Uscător",en:"Dryer",cat:"grooming",min:4,xp:25}
];
const socialItems=[
["people","👥","Oameni diferiți","Different people"],["children","🧒","Copii","Children"],["dogs","🐕","Câini calmi","Calm dogs"],["traffic","🚗","Trafic","Traffic"],["vacuum","🧹","Aspirator","Vacuum"],["dryer","💨","Uscător","Dryer"],["elevator","🛗","Lift","Elevator"],["car","🚙","Mașină","Car ride"],["vet","🩺","Cabinet veterinar","Vet clinic"],["groomer","✂️","Salon grooming","Groomer"],["surfaces","🪵","Suprafețe diferite","Different surfaces"],["cafe","☕","Cafenea / terasă","Cafe / terrace"]
];
const aloneTargets=[30,60,120,180,300,600,900,1200,1800,2700,3600];
const careDefaults={brush:1,eyes:1,teeth:1,ears:7,bath:21,nails:14,grooming:42};

const defaults={
 profile:{name:"Kygo",breed:"Poodle Toy",sex:"Mascul",age:3,weight:2.5,energy:"medium"},
 prefs:{lang:"ro",dark:false,notifications:false},
 xp:0,sessions:0,streak:1,bestStreak:1,lastActive:null,
 skills:Object.fromEntries(skills.map(s=>[s.id,0])),
 dailyDone:{},
 mealsPerDay:3,food:{brand:"Farmina",type:"Puppy Mini"},
 meals:[],water:[],weights:[{id:uid(),date:todayISO(),weight:2.5}],
 toilet:[],walks:[],social:{},alone:{level:0,success:0,history:[]},
 grooming:{done:[],appointments:[]},
 vaccines:[],medicines:[],vetVisits:[],journal:[],documents:[],events:[]
};
let data=load();
function load(){try{const p=JSON.parse(localStorage.getItem(KEY));return deepMerge(structuredClone(defaults),p||{})}catch{return structuredClone(defaults)}}
function deepMerge(a,b){for(const k in b){if(b[k]&&typeof b[k]==="object"&&!Array.isArray(b[k])&&a[k]&&typeof a[k]==="object"&&!Array.isArray(a[k]))a[k]=deepMerge(a[k],b[k]);else a[k]=b[k]}return a}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const lang=()=>data.prefs.lang;
const tSkill=s=>lang()==="ro"?s.ro:s.en;
const texts={
 ro:{"nav.home":"Acasă","nav.today":"Astăzi","nav.calendar":"Calendar","nav.training":"Dresaj","nav.toilet":"Toaletă","nav.food":"Mâncare","nav.walk":"Plimbare","nav.social":"Socializare","nav.alone":"Singur acasă","nav.grooming":"Grooming","nav.vet":"Veterinar","nav.journal":"Jurnal","nav.progress":"Progres","nav.documents":"Documente","nav.profile":"Profil","hero.eyebrow":"Coach & Care Hub","hero.hello":"Bună,","hero.start":"Începe ziua","care.score":"Today Care Score","stats.skills":"Abilități","stats.meals":"Mese","stats.toilet":"Toaletă","stats.walks":"Plimbări","home.next":"Următoarele activități","home.plan":"Planul zilei","home.week":"Ultimele 7 zile","home.quick":"Adaugă rapid","today.title":"Astăzi","today.timeline":"Calendarul zilei","today.adaptive":"Program adaptiv","calendar.title":"Calendar central","calendar.upcoming":"Următoarele 30 zile","training.title":"Dresaj & abilități","training.subtitle":"Fiecare abilitate are progres separat.","toilet.title":"Toaletă","toilet.subtitle":"Pipi, caca, accidente și intervale.","food.title":"Mâncare & apă","walk.title":"Plimbare","social.title":"Socializare","alone.title":"Singur acasă","grooming.title":"Grooming","vet.title":"Veterinar","journal.title":"Jurnal zilnic","progress.title":"Dashboard săptămânal","documents.title":"Documente","profile.title":"Profil"},
 en:{"nav.home":"Home","nav.today":"Today","nav.calendar":"Calendar","nav.training":"Training","nav.toilet":"Toilet","nav.food":"Food","nav.walk":"Walking","nav.social":"Socialization","nav.alone":"Home Alone","nav.grooming":"Grooming","nav.vet":"Veterinarian","nav.journal":"Journal","nav.progress":"Progress","nav.documents":"Documents","nav.profile":"Profile","hero.eyebrow":"Coach & Care Hub","hero.hello":"Hello,","hero.start":"Start the day","care.score":"Today Care Score","stats.skills":"Skills","stats.meals":"Meals","stats.toilet":"Toilet","stats.walks":"Walks","home.next":"Next activities","home.plan":"Today's plan","home.week":"Last 7 days","home.quick":"Quick add","today.title":"Today","today.timeline":"Today's calendar","today.adaptive":"Adaptive plan","calendar.title":"Central calendar","calendar.upcoming":"Next 30 days","training.title":"Training & skills","training.subtitle":"Each skill has its own progress.","toilet.title":"Toilet","toilet.subtitle":"Pee, poop, accidents and intervals.","food.title":"Food & water","walk.title":"Walking","social.title":"Socialization","alone.title":"Home Alone","grooming.title":"Grooming","vet.title":"Veterinarian","journal.title":"Daily journal","progress.title":"Weekly dashboard","documents.title":"Documents","profile.title":"Profile"}
};

function tr(key){return texts[lang()][key]||key}
function applyLang(){ $$("[data-i18n]").forEach(el=>el.textContent=tr(el.dataset.i18n)); $("#langBtn").textContent=lang()==="ro"?"🇷🇴 RO":"🇬🇧 EN"; renderAll() }
function pageName(p){const map={home:"nav.home",today:"nav.today",calendar:"nav.calendar",training:"nav.training",toilet:"nav.toilet",food:"nav.food",walk:"nav.walk",social:"nav.social",alone:"nav.alone",grooming:"nav.grooming",vet:"nav.vet",journal:"nav.journal",progress:"nav.progress",documents:"nav.documents",profile:"nav.profile"};return tr(map[p]||"nav.home")}
function setPage(p){$$(".page").forEach(x=>x.classList.remove("active"));$("#page-"+p)?.classList.add("active");$$(".nav-btn").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("#pageTitle").textContent=pageName(p);$("#sidebar").classList.remove("open");window.scrollTo({top:0,behavior:"smooth"});renderAll()}
function todayItems(arr){return arr.filter(x=>sameDay(x.date||x.start||x.datetime,new Date()))}
function addXP(n){data.xp+=n;data.sessions+=1;touchStreak();save()}
function touchStreak(){const d=todayISO();if(data.lastActive===d)return;if(!data.lastActive){data.lastActive=d;return}const prev=new Date(data.lastActive+"T12:00:00");const now=new Date(d+"T12:00:00");const diff=Math.round((now-prev)/86400000);data.streak=diff===1?data.streak+1:1;data.bestStreak=Math.max(data.bestStreak,data.streak);data.lastActive=d}
function dailyKey(k){return `${todayISO()}:${k}`}
function isDailyDone(k){return !!data.dailyDone[dailyKey(k)]}
function markDaily(k){data.dailyDone[dailyKey(k)]=true;touchStreak();save();renderAll()}
function ageStage(){const m=Number(data.profile.age)||3;if(m<6)return {label:lang()==="ro"?"Pui mic":"Young puppy",session:3,walk:10,training:["name","sit","recall","paws"]};if(m<12)return {label:lang()==="ro"?"Pui junior":"Junior puppy",session:5,walk:15,training:["recall","stay","leave","heel"]};if(m<24)return {label:lang()==="ro"?"Adolescent":"Adolescent",session:7,walk:20,training:["recall","heel","stay","place"]};return {label:lang()==="ro"?"Adult":"Adult",session:8,walk:25,training:["recall","heel","leave","place"]}}
function adaptivePlan(){
 const s=ageStage(); const plan=[
  {key:"meal1",icon:"🍗",title:lang()==="ro"?"Masa 1":"Meal 1",meta:"08:00"},
  {key:"toiletMorning",icon:"🚽",title:lang()==="ro"?"Ieșire toaletă":"Toilet break",meta:"after waking"},
  {key:"training",icon:"🎓",title:lang()==="ro"?`Dresaj ${s.session} min`:`Training ${s.session} min`,meta:tSkill(skills.find(x=>x.id===s.training[0]))},
  {key:"walk",icon:"🦮",title:lang()==="ro"?`Plimbare ${s.walk} min`:`Walk ${s.walk} min`,meta:"loose leash"},
  {key:"groom",icon:"🪮",title:lang()==="ro"?"Periaj scurt":"Short brushing",meta:"2–5 min"},
  {key:"brain",icon:"🧠",title:"Brain Gym",meta:"3–5 min"}
 ]; return plan;
}
function scoreCare(){let s=0;const p=adaptivePlan();s+=p.filter(x=>isDailyDone(x.key)).length*(60/p.length);const meals=todayItems(data.meals).length;s+=Math.min(15,(meals/Math.max(1,data.mealsPerDay))*15);if(todayItems(data.toilet).length)s+=10;if(todayItems(data.walks).length)s+=10;if(data.journal.some(x=>x.date===todayISO()))s+=5;return Math.round(Math.min(100,s))}
function scoreLabel(v){if(lang()==="en")return v>=85?"Excellent care":v>=65?"Great progress":v>=40?"Good start":"Start the routine";return v>=85?"Îngrijire excelentă":v>=65?"Progres foarte bun":v>=40?"Început bun":"Începe rutina"}
function centralEvents(){
 const ev=[...data.events.map(x=>({...x,icon:x.icon||"📌"}))];
 const mealTimes=["08:00","13:00","19:00"]; for(let i=0;i<data.mealsPerDay;i++) ev.push({id:"routineMeal"+i,date:todayISO(),time:mealTimes[i]||"18:00",title:lang()==="ro"?"Masă":"Meal",icon:"🍗",routine:true});
 ev.push({id:"rtrain",date:todayISO(),time:"10:00",title:lang()==="ro"?"Training":"Training",icon:"🎓",routine:true},{id:"rbrush",date:todayISO(),time:"17:00",title:lang()==="ro"?"Periaj":"Brushing",icon:"🪮",routine:true});
 data.grooming.appointments.forEach(x=>ev.push({id:x.id,date:x.date,time:x.time||"10:00",title:x.service||"Grooming",icon:"✂️"}));
 data.vetVisits.forEach(x=>ev.push({id:x.id,date:x.date,time:x.time||"10:00",title:x.reason||"Veterinar",icon:"🩺"}));
 data.vaccines.filter(x=>x.nextDate).forEach(x=>ev.push({id:"vx"+x.id,date:x.nextDate,time:"10:00",title:`${x.name} · reminder`,icon:"💉"}));
 data.medicines.filter(x=>x.nextDate).forEach(x=>ev.push({id:"med"+x.id,date:x.nextDate,time:x.time||"09:00",title:x.name,icon:"💊"}));
 return ev.sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))
}
function renderHome(){
 const score=scoreCare();$("#careScore").textContent=score;$("#scoreLabel").textContent=scoreLabel(score);$("#heroName").textContent=data.profile.name;$("#avatar").textContent=data.profile.name[0]?.toUpperCase()||"K";$("#streakStat").textContent=data.streak;$("#xpStat").textContent=data.xp;$("#skillsStat").textContent=`${Object.values(data.skills).filter(v=>v>=5).length}/${skills.length}`;$("#mealStat").textContent=`${todayItems(data.meals).length}/${data.mealsPerDay}`;$("#toiletStat").textContent=todayItems(data.toilet).length;$("#walkStat").textContent=todayItems(data.walks).length;
 const s=ageStage();$("#adaptiveSummary").textContent=lang()==="ro"?`Program ${s.label.toLowerCase()}: sesiuni de ~${s.session} min și plimbări ghidate de ~${s.walk} min.`:`${s.label} plan: ~${s.session}-minute training sessions and ~${s.walk}-minute guided walks.`;
 renderTimeline($("#homeTimeline"),centralEvents().filter(e=>e.date>=todayISO()).slice(0,7));
 renderPlan($("#adaptivePlan")); $("#planMinutes").textContent=`${adaptivePlan().reduce((a,x)=>a+(x.key==="training"?s.session:x.key==="walk"?s.walk:3),0)} min`;drawWeekly($("#weeklyChart"));
}
function renderPlan(target){target.innerHTML=adaptivePlan().map(x=>`<div class="check-row ${isDailyDone(x.key)?"done":""}"><button data-plan-done="${x.key}">${isDailyDone(x.key)?"✓":"○"}</button><div><strong>${x.icon} ${esc(x.title)}</strong><small>${esc(x.meta)}</small></div><span>+5</span></div>`).join("")}
function renderTimeline(target,items){target.innerHTML=items.length?items.map(x=>`<div class="timeline-item"><div class="timeline-icon">${x.icon||"📌"}</div><div><strong>${esc(x.title||x.type||"Event")}</strong><small>${x.note?esc(x.note):""}</small></div><time>${x.time||fmtDate(x.date,lang())}</time></div>`).join(""):`<div class="timeline-item"><div class="timeline-icon">✨</div><div><strong>${lang()==="ro"?"Nicio înregistrare":"No entries"}</strong><small>${lang()==="ro"?"Adaugă prima activitate.":"Add the first activity."}</small></div></div>`}
function renderToday(){ $("#todayDate").textContent=new Date().toLocaleDateString(lang()==="ro"?"ro-RO":"en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric"});$("#ageBadge").textContent=ageStage().label;renderPlan($("#todayAdaptive"));renderTimeline($("#todayTimeline"),centralEvents().filter(e=>e.date===todayISO()))}
let calOffset=0;
function renderCalendar(){const base=new Date();base.setMonth(base.getMonth()+calOffset);const y=base.getFullYear(),m=base.getMonth();$("#calLabel").textContent=base.toLocaleDateString(lang()==="ro"?"ro-RO":"en-GB",{month:"long",year:"numeric"});const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()+1);const ev=centralEvents();let html="";for(let i=0;i<35;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10),items=ev.filter(e=>e.date===iso);html+=`<div class="cal-day ${d.getMonth()!==m?"muted":""} ${iso===todayISO()?"today":""}" data-date="${iso}"><div class="cal-num">${d.getDate()}</div><div class="cal-events">${items.slice(0,3).map(e=>`<div class="cal-event">${e.icon||"📌"} ${esc(e.title)}</div>`).join("")}</div></div>`}$("#calendarGrid").innerHTML=html;const limit=new Date();limit.setDate(limit.getDate()+30);renderTimeline($("#upcomingList"),ev.filter(e=>new Date(e.date+"T23:59")>=new Date()&&new Date(e.date)<=limit).slice(0,30))}
function renderSkills(filter="all"){const list=skills.filter(s=>filter==="all"||s.cat===filter);$("#skillsGrid").innerHTML=list.map(s=>{const lv=data.skills[s.id]||0;return `<article class="skill-card"><div class="skill-icon">${s.icon}</div><h3>${esc(tSkill(s))}</h3><p>${lang()==="ro"?"Nivel separat de progres, cu distrageri crescute gradual.":"Separate skill progress with gradually increased distractions."}</p><div class="skill-levels">${[1,2,3,4,5].map(i=>`<i class="${i<=lv?"on":""}"></i>`).join("")}</div><small>${lang()==="ro"?"Nivel":"Level"} ${lv}/5 · ${s.min} min</small><button class="primary-btn" data-train="${s.id}">${lv>=5?"✓ Mastered":lang()==="ro"?"Antrenează":"Train"}</button></article>`}).join("")}
function renderToilet(){const td=todayItems(data.toilet);$("#peeToday").textContent=td.filter(x=>x.kind==="pee").length;$("#poopToday").textContent=td.filter(x=>x.kind==="poop").length;$("#accidentToday").textContent=td.filter(x=>x.accident).length;const last=[...data.toilet].reverse().find(x=>x.kind==="pee");$("#lastPee").textContent=last?fmtShort(last.datetime||last.date):"—";renderTimeline($("#toiletList"),[...data.toilet].reverse().slice(0,20).map(x=>({icon:x.kind==="pee"?"💧":"💩",title:x.accident?(lang()==="ro"?"Accident":"Accident"):(x.kind==="pee"?"Pipi":"Caca"),note:x.location||"",time:fmtShort(x.datetime||x.date),date:(x.datetime||x.date).slice(0,10)})));drawToilet($("#toiletChart"))}
function renderFood(){const tm=todayItems(data.meals),grams=tm.reduce((a,x)=>a+Number(x.grams||0),0),water=todayItems(data.water).reduce((a,x)=>a+Number(x.ml||0),0);$("#mealsToday").textContent=`${tm.length}/${data.mealsPerDay}`;$("#gramsToday").textContent=`${grams}g`;$("#waterToday").textContent=`${water}ml`;$("#weightToday").textContent=`${data.profile.weight}kg`;$("#foodBrand").value=data.food.brand;$("#foodType").value=data.food.type;$("#mealsPerDay").value=data.mealsPerDay;renderTimeline($("#mealList"),[...data.meals].reverse().slice(0,20).map(x=>({icon:"🍗",title:`${x.grams}g · ${x.type||data.food.type}`,note:data.food.brand,time:x.time,date:x.date})));drawWeight($("#weightChart"))}
let walkTimer=null,walkStart=null,walkCounters={loose:0,recall:0,distraction:0};
function renderWalk(){renderTimeline($("#walkHistory"),[...data.walks].reverse().slice(0,20).map(x=>({icon:"🦮",title:`${x.minutes||0} min`,note:`Loose ${x.loose||0} · Recall ${x.recall||0} · Distr. ${x.distraction||0}`,date:x.date,time:x.time})))}
function renderSocial(){$("#socialGrid").innerHTML=socialItems.map(([id,icon,ro,en])=>`<article class="social-card ${data.social[id]?"done":""}"><div style="font-size:28px">${icon}</div><h3>${lang()==="ro"?ro:en}</h3><p>${data.social[id]?("✓ "+(lang()==="ro"?"Experiență bifată":"Completed")):(lang()==="ro"?"Expunere scurtă, pozitivă și fără forțare.":"Short, positive exposure without forcing.")}</p><button class="${data.social[id]?"secondary-btn":"primary-btn"}" data-social="${id}">${data.social[id]?"✓":lang()==="ro"?"Marchează":"Mark done"}</button></article>`).join("")}
function renderAlone(){const lv=data.alone.level;$("#aloneLevel").textContent=lv+1;$("#aloneTarget").textContent=formatSecs(aloneTargets[lv]||aloneTargets.at(-1));$("#aloneSuccess").textContent=data.alone.success;$("#aloneSteps").innerHTML=aloneTargets.slice(0,10).map((s,i)=>`<div class="alone-step ${i===lv?"active":""} ${i<lv?"done":""}"><strong>${i+1}</strong><small>${formatSecs(s)}</small></div>`).join("");renderTimeline($("#aloneHistory"),[...data.alone.history].reverse().slice(0,20).map(x=>({icon:x.success?"✅":"↩️",title:x.success?(lang()==="ro"?"Sesiune reușită":"Successful session"):(lang()==="ro"?"Prea dificil":"Too difficult"),note:formatSecs(x.seconds),date:x.date,time:x.time})))}
function formatSecs(s){if(s<60)return `${s} sec`;if(s<3600)return `${Math.round(s/60)} min`;return `${(s/3600).toFixed(1)} h`}
function renderGrooming(){const types=[["brush","🪮","Periaj"],["bath","🛁","Baie"],["nails","💅","Unghii"],["ears","👂","Urechi"]];$("#groomingCards").innerHTML=types.map(([id,ic,n])=>{const last=[...data.grooming.done].reverse().find(x=>x.type===id);return `<article class="stat"><span>${ic}</span><small>${n}</small><strong>${last?fmtDate(last.date,lang()):"—"}</strong><button class="tiny-btn" data-groom-done="${id}">✓ Făcut</button></article>`}).join("");const routine=[["brush","🪮","Periaj","Daily"],["eyes","👁️","Ochi","Daily"],["teeth","🦷","Dinți","Daily"],["ears","👂","Urechi","Weekly"],["bath","🛁","Baie","Periodic"],["nails","💅","Unghii","As needed"]];$("#groomingRoutine").innerHTML=routine.map(([id,ic,ro,en])=>`<div class="check-row"><button data-groom-done="${id}">○</button><div><strong>${ic} ${lang()==="ro"?ro:en}</strong><small>${careDefaults[id]===1?(lang()==="ro"?"Zilnic":"Daily"):`~${careDefaults[id]}d`}</small></div></div>`).join("");const items=[...data.grooming.appointments.map(x=>({icon:"✂️",title:x.service,note:x.salon,date:x.date,time:x.time||"10:00"})),...data.grooming.done.map(x=>({icon:"✨",title:x.type,note:"done",date:x.date,time:x.time||""}))].sort((a,b)=>b.date.localeCompare(a.date));renderTimeline($("#groomingTimeline"),items.slice(0,20))}
function renderVet(){$("#vaccineCount").textContent=data.vaccines.length;$("#medicineCount").textContent=data.medicines.length;$("#dewormCount").textContent=data.medicines.filter(x=>x.type==="deworm").length;$("#visitCount").textContent=data.vetVisits.length;renderTimeline($("#vaccineList"),[...data.vaccines].reverse().map(x=>({icon:"💉",title:x.name,note:x.nextDate?`Next: ${x.nextDate}`:"",date:x.date,time:""})));renderTimeline($("#medicineList"),[...data.medicines].reverse().map(x=>({icon:"💊",title:x.name,note:x.type||"",date:x.date,time:x.time||""})));renderTimeline($("#vetTimeline"),[...data.vetVisits].reverse().map(x=>({icon:"🩺",title:x.reason,note:x.clinic||x.notes||"",date:x.date,time:x.time||""})))}
function renderJournal(){const j=data.journal.find(x=>x.date===todayISO());if(j){$("#journalMood").value=j.mood;$("#journalAppetite").value=j.appetite;$("#journalSleep").value=j.sleep;$("#journalEnergy").value=j.energy;$("#journalNotes").value=j.notes}renderTimeline($("#journalHistory"),[...data.journal].reverse().slice(0,14).map(x=>({icon:"📔",title:`${x.mood} · ${x.sleep||0}h`,note:x.notes,date:x.date,time:""})))}
function renderProgress(){$("#progressXp").textContent=data.xp;$("#progressSessions").textContent=data.sessions;const vals=Object.values(data.skills);$("#progressMastery").textContent=`${Math.round(vals.reduce((a,b)=>a+b,0)/(skills.length*5)*100)}%`;$("#progressCare").textContent=scoreCare();$("#skillProgressList").innerHTML=skills.map(s=>`<div class="skill-progress-item"><header><strong>${s.icon} ${esc(tSkill(s))}</strong><span>${data.skills[s.id]||0}/5</span></header><div class="progress-track"><span style="width:${(data.skills[s.id]||0)*20}%"></span></div></div>`).join("");drawCare($("#careChart"))}
function renderDocs(){$("#documentsGrid").innerHTML=data.documents.length?data.documents.map(x=>`<article class="doc-card"><div class="doc-icon">${x.type==="passport"?"📕":"📄"}</div><h3>${esc(x.name)}</h3><small>${esc(x.note||"")}</small><small>${fmtDate(x.date,lang())}</small></article>`).join(""):`<article class="doc-card"><div class="doc-icon">📂</div><h3>${lang()==="ro"?"Niciun document":"No documents"}</h3><small>${lang()==="ro"?"Adaugă pașaportul de vaccinare, pedigree sau analize.":"Add vaccination passport, pedigree or lab results."}</small></article>`}
function renderProfile(){const p=data.profile;$("#profileName").textContent=p.name;$("#profileMeta").textContent=`${p.breed} · ${p.sex} · ${p.age} luni`;$("#profileNameInput").value=p.name;$("#profileBreedInput").value=p.breed;$("#profileSexInput").value=p.sex;$("#profileAgeInput").value=p.age;$("#profileWeightInput").value=p.weight;$("#profileEnergyInput").value=p.energy}
function renderAll(){document.body.classList.toggle("dark",data.prefs.dark);$("#themeBtn").textContent=data.prefs.dark?"☀️ Light":"🌙 Dark";renderHome();renderToday();renderCalendar();renderSkills($("#skillFilters .active")?.dataset.filter||"all");renderToilet();renderFood();renderWalk();renderSocial();renderAlone();renderGrooming();renderVet();renderJournal();renderProgress();renderDocs();renderProfile()}

function last7(){return [...Array(7)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d.toISOString().slice(0,10)})}
function drawLineChart(canvas,series,labels){if(!canvas)return;const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue("--line");ctx.fillStyle=getComputedStyle(document.body).getPropertyValue("--muted");ctx.font="12px sans-serif";for(let i=0;i<5;i++){const y=30+i*(h-60)/4;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-20,y);ctx.stroke()}const max=Math.max(1,...series);ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue("--primary");ctx.lineWidth=4;ctx.beginPath();series.forEach((v,i)=>{const x=50+i*(w-80)/(series.length-1||1),y=h-35-(v/max)*(h-80);i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillText(labels[i],x-12,h-12)});ctx.stroke()}
function drawWeekly(c){const days=last7(),vals=days.map(d=>data.meals.filter(x=>x.date===d).length+data.toilet.filter(x=>(x.datetime||x.date).slice(0,10)===d).length+data.walks.filter(x=>x.date===d).length+Object.keys(data.dailyDone).filter(k=>k.startsWith(d)&&data.dailyDone[k]).length);drawLineChart(c,vals,days.map(d=>d.slice(5)))}
function drawToilet(c){const days=last7(),vals=days.map(d=>data.toilet.filter(x=>(x.datetime||x.date).slice(0,10)===d).length);drawLineChart(c,vals,days.map(d=>d.slice(5)))}
function drawWeight(c){const x=data.weights.slice(-10);drawLineChart(c,x.map(v=>Number(v.weight)),x.map(v=>v.date.slice(5)))}
function drawCare(c){drawWeekly(c)}

function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2300)}
function openModal(html){$("#modalContent").innerHTML=html;$("#modal").classList.add("open")}
function closeModal(){ $("#modal").classList.remove("open") }
function inputModal(title,fields,onSave){openModal(`<h2>${title}</h2><div class="form-grid">${fields.map(f=>`<label>${f.label}${f.type==="textarea"?`<textarea id="${f.id}" rows="3">${f.value||""}</textarea>`:`<input id="${f.id}" type="${f.type||"text"}" value="${f.value||""}" ${f.step?`step="${f.step}"`:""}>`}</label>`).join("")}</div><div class="modal-actions"><button class="secondary-btn" data-modal-cancel>Anulează</button><button class="primary-btn" id="modalSave">Salvează</button></div>`);$("#modalSave").onclick=()=>onSave(Object.fromEntries(fields.map(f=>[f.id,$("#"+f.id).value])))}

function addQuick(type){
 if(type==="pee"||type==="poop"){data.toilet.push({id:uid(),kind:type,datetime:new Date().toISOString(),location:"afară",accident:false});markDaily("toiletMorning");toast(type==="pee"?"Pipi ✓":"Caca ✓")}
 if(type==="meal"){data.meals.push({id:uid(),date:todayISO(),time:nowTime(),grams:30,type:data.food.type});if(todayItems(data.meals).length===1)markDaily("meal1");save();toast("Masă adăugată 🍗")}
 if(type==="walk"){startWalk()}
 if(type==="sleep"){inputModal("Somn",[{id:"hours",label:"Ore",type:"number",value:"1",step:".5"}],v=>{data.journal.push({id:uid(),date:todayISO(),mood:"😴 Somn",appetite:"",sleep:Number(v.hours),energy:2,notes:"Nap"});save();closeModal();renderAll();toast("Somn înregistrat 😴")})}
 if(type==="medicine") addMedicine();
 renderAll()
}
function trainSkill(id){const s=skills.find(x=>x.id===id);const lv=data.skills[id]||0;openModal(`<span class="eyebrow">Skill Training</span><h2>${s.icon} ${esc(tSkill(s))}</h2><p>${lang()==="ro"?"Sesiune scurtă cu recompense mici și criterii clare.":"Short session with small rewards and clear criteria."}</p><div class="panel"><strong>${lang()==="ro"?"Nivel curent":"Current level"}: ${lv}/5</strong><p>${lang()==="ro"?"1 Învață · 2 Cu ajutor · 3 Fără ajutor · 4 Distrageri · 5 Stăpânit":"1 Learn · 2 Assisted · 3 Independent · 4 Distractions · 5 Mastered"}</p></div><div class="modal-actions"><button class="secondary-btn" data-modal-cancel>Cancel</button><button class="primary-btn" id="completeSkill">✓ ${s.min} min</button></div>`);$("#completeSkill").onclick=()=>{data.skills[id]=Math.min(5,lv+1);addXP(s.xp);markDaily("training");closeModal();renderAll();toast(`+${s.xp} XP ⭐`)}}
function emergency(){openModal(`<span class="eyebrow">Emergency Commands</span><h2>🚨 ${lang()==="ro"?"Comenzi prioritare":"Priority commands"}</h2>${["recall","stay","leave","wait"].map(id=>{const s=skills.find(x=>x.id===id);return `<div class="check-row"><span>${s.icon}</span><div><strong>${tSkill(s)}</strong><small>${lang()==="ro"?"Exersează întâi în mediu sigur, apoi crește distragerile.":"Practice in a safe environment first, then increase distractions."}</small></div><button data-train="${id}">▶</button></div>`}).join("")}`)}
function startWalk(){if(walkTimer){finishWalk();return}walkStart=Date.now();walkCounters={loose:0,recall:0,distraction:0};$("#startWalkBtn").textContent="■ Stop";walkTimer=setInterval(()=>{const s=Math.floor((Date.now()-walkStart)/1000);$("#walkTimer").textContent=`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`},1000)}
function finishWalk(){const mins=Math.max(1,Math.round((Date.now()-walkStart)/60000));clearInterval(walkTimer);walkTimer=null;data.walks.push({id:uid(),date:todayISO(),time:nowTime(),minutes:mins,...walkCounters});addXP(20);markDaily("walk");$("#startWalkBtn").textContent="▶ Start Walking Mode";$("#walkTimer").textContent="00:00";renderAll();toast("Plimbare salvată 🦮")}
function addToilet(){inputModal("Toilet Tracker",[{id:"kind",label:"Tip (pee/poop)",value:"pee"},{id:"location",label:"Loc",value:"afară"},{id:"accident",label:"Accident? (da/nu)",value:"nu"}],v=>{data.toilet.push({id:uid(),kind:v.kind==="poop"?"poop":"pee",datetime:new Date().toISOString(),location:v.location,accident:/da|yes|true/i.test(v.accident)});save();closeModal();renderAll();toast("Înregistrare salvată 🚽")})}
function addMeal(){inputModal("Meal Tracker",[{id:"grams",label:"Cantitate (g)",type:"number",value:"30"},{id:"type",label:"Tip hrană",value:data.food.type},{id:"time",label:"Ora",type:"time",value:nowTime()}],v=>{data.meals.push({id:uid(),date:todayISO(),time:v.time,grams:Number(v.grams),type:v.type});save();closeModal();renderAll();toast("Masă salvată 🍗")})}
function addWeight(){inputModal("Weight Tracker",[{id:"weight",label:"Greutate kg",type:"number",step:".1",value:data.profile.weight}],v=>{const w=Number(v.weight);data.profile.weight=w;data.weights.push({id:uid(),date:todayISO(),weight:w});save();closeModal();renderAll();toast("Greutate actualizată ⚖️")})}
function addEvent(date=todayISO()){inputModal("Calendar Event",[{id:"date",label:"Data",type:"date",value:date},{id:"time",label:"Ora",type:"time",value:"10:00"},{id:"title",label:"Titlu",value:"Activitate"},{id:"icon",label:"Emoji",value:"📌"}],v=>{data.events.push({id:uid(),date:v.date,time:v.time,title:v.title,icon:v.icon});save();closeModal();renderAll();toast("Activitate adăugată 🗓️")})}
function addGrooming(){inputModal("Grooming",[{id:"date",label:"Data",type:"date",value:todayISO()},{id:"time",label:"Ora",type:"time",value:"10:00"},{id:"service",label:"Serviciu",value:"Grooming complet"},{id:"salon",label:"Salon",value:""}],v=>{data.grooming.appointments.push({id:uid(),...v});save();closeModal();renderAll();toast("Programare salvată ✂️")})}
function addVet(){inputModal("Vizită veterinar",[{id:"date",label:"Data",type:"date",value:todayISO()},{id:"time",label:"Ora",type:"time",value:"10:00"},{id:"reason",label:"Motiv",value:"Control"},{id:"clinic",label:"Clinică",value:""},{id:"notes",label:"Observații",type:"textarea"}],v=>{data.vetVisits.push({id:uid(),...v});save();closeModal();renderAll();toast("Vizită salvată 🩺")})}
function addVaccine(){inputModal("Vaccin",[{id:"name",label:"Nume vaccin",value:"Vaccin"},{id:"date",label:"Data",type:"date",value:todayISO()},{id:"nextDate",label:"Următoarea dată",type:"date",value:""}],v=>{data.vaccines.push({id:uid(),...v});save();closeModal();renderAll();toast("Vaccin adăugat 💉")})}
function addMedicine(){inputModal("Medicament / tratament",[{id:"name",label:"Nume",value:""},{id:"type",label:"Tip",value:"medicine"},{id:"date",label:"Data",type:"date",value:todayISO()},{id:"time",label:"Ora",type:"time",value:nowTime()},{id:"nextDate",label:"Reminder următor",type:"date",value:""}],v=>{data.medicines.push({id:uid(),...v});save();closeModal();renderAll();toast("Tratament salvat 💊")})}
function addDoc(){inputModal("Document",[{id:"name",label:"Nume",value:"Pașaport vaccinare"},{id:"type",label:"Tip",value:"passport"},{id:"date",label:"Data",type:"date",value:todayISO()},{id:"note",label:"Notă",value:""}],v=>{data.documents.push({id:uid(),...v});save();closeModal();renderAll();toast("Document adăugat 📄")})}
function startAlone(){const sec=aloneTargets[data.alone.level]||aloneTargets.at(-1);openModal(`<span class="eyebrow">Alone Home</span><h2>🏠 ${formatSecs(sec)}</h2><p>${lang()==="ro"?"Plecare neutră, activitate calmă, revenire înainte de escaladarea stresului.":"Neutral departure, calm activity, return before stress escalates."}</p><div class="modal-actions"><button class="secondary-btn" id="aloneFail">${lang()==="ro"?"Prea greu":"Too hard"}</button><button class="primary-btn" id="aloneOk">✓ ${lang()==="ro"?"Reușit":"Success"}</button></div>`);$("#aloneOk").onclick=()=>{data.alone.history.push({id:uid(),date:todayISO(),time:nowTime(),seconds:sec,success:true});data.alone.success++;if(data.alone.success%2===0)data.alone.level=Math.min(aloneTargets.length-1,data.alone.level+1);save();closeModal();renderAll();toast("Alone Home +1 ✅")};$("#aloneFail").onclick=()=>{data.alone.history.push({id:uid(),date:todayISO(),time:nowTime(),seconds:sec,success:false});if(data.alone.level>0)data.alone.level--;save();closeModal();renderAll()}}
function showAI(){const s=ageStage(),score=scoreCare();const rec=[];if(todayItems(data.meals).length<data.mealsPerDay)rec.push(lang()==="ro"?"Mai ai mese de înregistrat astăzi.":"You still have meals to log today.");if(!todayItems(data.walks).length)rec.push(lang()==="ro"?`Poți face o plimbare ghidată de ~${s.walk} minute.`:`Try a guided ~${s.walk}-minute walk.`);if(!isDailyDone("training"))rec.push(lang()==="ro"?`Sesiune recomandată: ${tSkill(skills.find(x=>x.id===s.training[0]))}, ~${s.session} minute.`:`Recommended session: ${tSkill(skills.find(x=>x.id===s.training[0]))}, ~${s.session} minutes.`);if(score>80)rec.push(lang()==="ro"?"Rutina de azi arată foarte bine; păstrează sesiunile scurte.":"Today's routine looks great; keep sessions short.");$("#aiSuggestions").innerHTML=rec.map(x=>`<div class="ai-suggestion">✨ ${esc(x)}</div>`).join("");$("#aiModal").classList.add("open")}
function aiAnswer(q){q=q.toLowerCase();if(/mușc|bite/.test(q))return lang()==="ro"?"Oprește jocul cu mâinile, redirecționează către o jucărie și recompensează alegerea corectă.":"Stop hand play, redirect to a toy, and reward the correct choice.";if(/vino|recall|come/.test(q))return lang()==="ro"?"Începe în interior, spune comanda o singură dată, îndepărtează-te ușor și recompensează generos sosirea.":"Start indoors, say the cue once, move away slightly, and reward arrival generously.";if(/lătr|bark/.test(q))return lang()==="ro"?"Identifică declanșatorul, mărește distanța și recompensează pauzele de liniște.":"Identify the trigger, increase distance, and reward quiet pauses.";return lang()==="ro"?"Alege un singur comportament, fă o sesiune de 3–5 minute și oprește-te cât timp încă este motivat.":"Choose one behavior, train for 3–5 minutes, and stop while motivation is still high."}
async function enableNotifications(){if(!("Notification" in window)){toast("Notifications unavailable");return}const p=await Notification.requestPermission();data.prefs.notifications=p==="granted";save();toast(p==="granted"?"Notificări activate 🔔":"Notificări neactivate")}
function scheduleBrowserReminder(){if(!data.prefs.notifications||Notification.permission!=="granted")return;const upcoming=centralEvents().find(e=>e.date===todayISO()&&e.time>=nowTime());if(upcoming)new Notification("Poodle Coach",{body:`${upcoming.time} ${upcoming.icon||""} ${upcoming.title}`})}

document.addEventListener("click",e=>{
 const nav=e.target.closest("[data-page]");if(nav)setPage(nav.dataset.page);
 const go=e.target.closest("[data-go]");if(go)setPage(go.dataset.go);
 const pd=e.target.closest("[data-plan-done]");if(pd)markDaily(pd.dataset.planDone);
 const trn=e.target.closest("[data-train]");if(trn)trainSkill(trn.dataset.train);
 const q=e.target.closest("[data-quick]");if(q)addQuick(q.dataset.quick);
 const sf=e.target.closest("[data-social]");if(sf){data.social[sf.dataset.social]=!data.social[sf.dataset.social];save();renderSocial()}
 const gd=e.target.closest("[data-groom-done]");if(gd){data.grooming.done.push({id:uid(),type:gd.dataset.groomDone,date:todayISO(),time:nowTime()});save();renderGrooming();toast("Grooming ✓")}
 const wa=e.target.closest("[data-walk-action]");if(wa&&walkTimer){const a=wa.dataset.walkAction;if(a==="pee"||a==="poop"){data.toilet.push({id:uid(),kind:a,datetime:new Date().toISOString(),location:"plimbare",accident:false});save()}else{walkCounters[a]++;$("#looseLeashCount").textContent=walkCounters.loose;$("#walkRecallCount").textContent=walkCounters.recall;$("#distractionCount").textContent=walkCounters.distraction}}
 const cd=e.target.closest(".cal-day");if(cd&&!e.target.closest(".cal-event"))addEvent(cd.dataset.date);
 if(e.target.matches("[data-modal-cancel]"))closeModal()
});
$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
$("#themeBtn").onclick=()=>{data.prefs.dark=!data.prefs.dark;save();renderAll()};
$("#langBtn").onclick=()=>{data.prefs.lang=lang()==="ro"?"en":"ro";save();applyLang()};
$("#notifyBtn").onclick=enableNotifications;
$("#aiCoachBtn").onclick=showAI;$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.remove("open"));
$("#askAiBtn").onclick=()=>{const a=aiAnswer($("#aiInput").value);$("#aiSuggestions").innerHTML+=`<div class="ai-suggestion">🤖 ${esc(a)}</div>`};
$("#modalClose").onclick=closeModal;$("#modal").addEventListener("click",e=>{if(e.target===$("#modal"))closeModal()});
$("#addEventBtn").onclick=()=>addEvent();$("#calendarAddBtn").onclick=()=>addEvent();$("#calPrev").onclick=()=>{calOffset--;renderCalendar()};$("#calNext").onclick=()=>{calOffset++;renderCalendar()};
$("#emergencyBtn").onclick=emergency;$("#toiletAddBtn").onclick=addToilet;$("#mealAddBtn").onclick=addMeal;$("#waterBtn").onclick=()=>{data.water.push({id:uid(),date:todayISO(),time:nowTime(),ml:50});save();renderFood();toast("+50 ml 💧")};$("#weightBtn").onclick=addWeight;
$("#saveFoodBtn").onclick=()=>{data.food.brand=$("#foodBrand").value;data.food.type=$("#foodType").value;data.mealsPerDay=Number($("#mealsPerDay").value)||3;save();renderAll();toast("Profil hrană salvat")};
$("#startWalkBtn").onclick=startWalk;$("#startAloneBtn").onclick=startAlone;$("#groomingAddBtn").onclick=addGrooming;$("#vetVisitBtn").onclick=addVet;$("#vaccineAddBtn").onclick=addVaccine;$("#medicineAddBtn").onclick=addMedicine;$("#docAddBtn").onclick=addDoc;
$("#saveJournalBtn").onclick=()=>{const obj={id:uid(),date:todayISO(),mood:$("#journalMood").value,appetite:$("#journalAppetite").value,sleep:Number($("#journalSleep").value)||0,energy:Number($("#journalEnergy").value)||3,notes:$("#journalNotes").value};const i=data.journal.findIndex(x=>x.date===todayISO());if(i>=0)data.journal[i]=obj;else data.journal.push(obj);save();renderAll();toast("Jurnal salvat 📔")};
$("#saveProfileBtn").onclick=()=>{data.profile={name:$("#profileNameInput").value||"Kygo",breed:$("#profileBreedInput").value,sex:$("#profileSexInput").value,age:Number($("#profileAgeInput").value)||3,weight:Number($("#profileWeightInput").value)||2.5,energy:$("#profileEnergyInput").value};save();renderAll();toast("Profil salvat 🐩")};
$("#completeDayBtn").onclick=()=>{adaptivePlan().forEach(x=>data.dailyDone[dailyKey(x.key)]=true);touchStreak();save();renderAll();toast("Zi completată ✅")};
$("#skillFilters").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;$$("#skillFilters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSkills(b.dataset.filter)});

let deferredPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").hidden=false});
$("#installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").hidden=true};
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
applyLang();renderAll();setTimeout(scheduleBrowserReminder,1200);
