/* v9 health: reminders, food calculator, toilet prediction, symptoms, photo journal, weight trend */
(() => {
const V=window.PoodleV9,q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],mk=()=>crypto.randomUUID?.()||`id-${Date.now()}-${Math.random().toString(36).slice(2)}`;
if(!V)return;
function foodEstimate(){const kg=Math.max(.5,+data.profile.weight||1),age=+data.profile.age||12,kcalKg=Math.max(1,+data.food.kcalPerKg||3900),rer=70*Math.pow(kg,.75);let f=age<4?3:age<12?2:(data.profile.energy==='high'?1.8:data.profile.energy==='calm'?1.4:1.6);const kcal=rer*f;return{rer:Math.round(rer),kcal:Math.round(kcal),grams:Math.round(kcal/(kcalKg/1000))}}
function peePrediction(){const a=data.toilet.filter(x=>x.kind==='pee').map(x=>new Date(x.datetime||x.date).getTime()).filter(Number.isFinite).sort((a,b)=>a-b).slice(-30);if(a.length<3)return null;const d=[];for(let i=1;i<a.length;i++){const z=a[i]-a[i-1];if(z>600000&&z<43200000)d.push(z)}if(!d.length)return null;d.sort((a,b)=>a-b);const m=d[Math.floor(d.length/2)];return{minutes:Math.round(m/60000),due:new Date(a.at(-1)+m)}}
V.foodEstimate=foodEstimate;V.peePrediction=peePrediction;
function injectPredictions(){if(!q('#v9PredictionPanel')){const p=document.createElement('article');p.className='panel';p.id='v9PredictionPanel';q('#page-food')?.append(p)}const f=foodEstimate(),p=peePrediction();q('#v9PredictionPanel').innerHTML=`<div class="panel-head"><div><span class="eyebrow">Smart Health</span><h3>Predicții & calculator</h3></div></div><div class="grid two"><div class="metric-v9">🥣 <div><small>Estimare hrană</small><strong>~${f.grams} g/zi · ${f.kcal} kcal</strong><span>RER ${f.rer} kcal · punct de pornire, ajustează după etichetă, BCS și veterinar.</span></div></div><div class="metric-v9">🚽 <div><small>Predicție toaletă</small><strong>${p?`~${p.minutes} min interval`:'Mai multe date necesare'}</strong><span>${p?`Următoarea estimare: ${p.due.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`:'Înregistrează cel puțin 3 episoade.'}</span></div></div></div><div class="form-grid"><label>kcal/kg hrană<input id="v9Kcal" type="number" value="${data.food.kcalPerKg||3900}"></label><label>Greutate țintă min/max (setată cu veterinarul)<div style="display:flex;gap:6px"><input id="v9Tmin" type="number" step=".1" value="${data.targetWeight?.min??''}" placeholder="min"><input id="v9Tmax" type="number" step=".1" value="${data.targetWeight?.max??''}" placeholder="max"></div></label></div><button class="tiny-btn" id="v9SaveHealthCalc">Save</button>`;q('#v9SaveHealthCalc').onclick=()=>{data.food.kcalPerKg=+q('#v9Kcal').value||3900;data.targetWeight={min:+q('#v9Tmin').value||null,max:+q('#v9Tmax').value||null,source:'vet'};save();V.healthRefresh()}}
function symptoms(){if(!q('#symptomPanel')){const p=document.createElement('article');p.className='panel';p.id='symptomPanel';p.innerHTML='<div class="panel-head"><div><h3>❤️ Tracker simptome</h3><small>Jurnal de observații; aplicația nu pune diagnostice.</small></div><button class="tiny-btn" id="addSymptomV9">+ Simptom</button></div><div id="symptomList" class="timeline"></div>';q('#page-vet')?.append(p);q('#addSymptomV9').onclick=()=>inputModal('Simptom',[{id:'name',label:'Simptom / observație',value:''},{id:'severity',label:'Severitate: mild / monitor / urgent',value:'monitor'},{id:'note',label:'Notă',value:''}],v=>{data.symptoms.push({id:mk(),date:todayISO(),time:nowTime(),...v});save();closeModal();symptoms();if(v.severity.toLowerCase()==='urgent')alert('Ai marcat simptomul ca urgent. Contactează medicul veterinar / serviciul veterinar de urgență.')})}renderTimeline(q('#symptomList'),[...data.symptoms].reverse().slice(0,20).map(x=>({icon:x.severity==='urgent'?'🚨':'❤️',title:x.name,note:x.note,date:x.date,time:x.time})))}
function compress(file){return new Promise((res,rej)=>{const i=new Image(),u=URL.createObjectURL(file);i.onload=()=>{const m=900,s=Math.min(1,m/Math.max(i.width,i.height)),c=document.createElement('canvas');c.width=Math.round(i.width*s);c.height=Math.round(i.height*s);c.getContext('2d').drawImage(i,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',.78))};i.onerror=rej;i.src=u})}
async function addPhoto(file){data.photos.push({id:mk(),date:todayISO(),data:await compress(file),note:''});save();photos();toast('📸 ✓')}
function photos(){if(!q('#photoJournalPanel')){const p=document.createElement('article');p.className='panel';p.id='photoJournalPanel';p.innerHTML='<div class="panel-head"><div><h3>📸 Jurnal foto</h3><small>Creștere · grooming before/after</small></div><label class="tiny-btn file-btn">+ Foto<input id="v9Photo" type="file" accept="image/*"></label></div><div id="v9PhotoGrid" class="photo-grid"></div>';q('#page-documents')?.append(p);q('#v9Photo').onchange=e=>e.target.files[0]&&addPhoto(e.target.files[0])}q('#v9PhotoGrid').innerHTML=[...data.photos].reverse().map(x=>`<figure><img src="${x.data}" alt="Pet photo"><figcaption>${x.date}<button class="tiny-btn danger" data-photo-del="${x.id}">×</button></figcaption></figure>`).join('')||'<div class="empty-v9">Adaugă prima fotografie.</div>';qa('[data-photo-del]').forEach(b=>b.onclick=()=>{data.photos=data.photos.filter(x=>x.id!==b.dataset.photoDel);save();photos()})}
function vaccineTemplate(){if(q('#vaccineTemplateBtn'))return;const b=document.createElement('button');b.className='tiny-btn';b.id='vaccineTemplateBtn';b.textContent='＋ Puppy vaccine template';q('#vaccineList')?.closest('.panel')?.querySelector('.panel-head')?.append(b);b.onclick=()=>{if(!confirm('Adaug un șablon editabil de 3 repere pentru schema puppy? Confirmă datele cu medicul veterinar.'))return;const base=new Date();[0,21,42].forEach((n,i)=>{const d=new Date(base);d.setDate(d.getDate()+n);data.vaccines.push({id:mk(),name:`Core puppy template #${i+1}`,date:d.toISOString().slice(0,10),nextDate:i<2?new Date(d.getTime()+21*86400000).toISOString().slice(0,10):'',template:true})});save();renderAll();toast('Vaccination template ✓')}}
function reminderItems(){const out=[];centralEvents().forEach(e=>e.date>=todayISO()&&out.push({...e,key:`e:${e.id}:${e.date}:${e.time}`}));data.documents.filter(x=>x.expiry).forEach(x=>out.push({date:x.expiry,time:'09:00',title:`Document: ${x.name}`,icon:'📄',key:`d:${x.id}:${x.expiry}`}));return out}
V.updateBadge=()=>{const n=adaptivePlan().filter(x=>!isDailyDone(x.key)).length+Math.max(0,data.mealsPerDay-todayItems(data.meals).length);if('setAppBadge'in navigator){n?navigator.setAppBadge(n).catch(()=>{}):navigator.clearAppBadge?.().catch(()=>{})}}
async function due(){if(!data.prefs.notifications||Notification.permission!=='granted')return;const root=V.root(),hm=nowTime();for(const x of reminderItems().filter(x=>x.date===todayISO()&&x.time<=hm)){if(root.reminderLog[x.key])continue;new Notification('Poodle Coach',{body:`${x.time} ${x.icon||''} ${x.title}`,icon:'icon-192.png'});root.reminderLog[x.key]=new Date().toISOString()}save()}
setInterval(due,60000);setTimeout(due,2500);
const oldDraw=drawWeight;drawWeight=function(c){if(!c)return;const a=data.weights.slice(-14),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);if(!a.length)return;const vals=a.map(x=>+x.weight),rr=[...vals];if(data.targetWeight?.min)rr.push(data.targetWeight.min);if(data.targetWeight?.max)rr.push(data.targetWeight.max);const lo=Math.min(...rr)*.92,hi=Math.max(...rr)*1.08,y=v=>h-35-(v-lo)/(hi-lo||1)*(h-70);if(data.targetWeight?.min&&data.targetWeight?.max){ctx.fillStyle='rgba(98,139,115,.14)';ctx.fillRect(45,y(data.targetWeight.max),w-70,y(data.targetWeight.min)-y(data.targetWeight.max))}ctx.strokeStyle=getComputedStyle(document.body).getPropertyValue('--primary');ctx.lineWidth=4;ctx.beginPath();a.forEach((p,i)=>{const x=50+i*(w-80)/(a.length-1||1);i?ctx.lineTo(x,y(+p.weight)):ctx.moveTo(x,y(+p.weight));ctx.fillStyle=getComputedStyle(document.body).getPropertyValue('--muted');ctx.fillText(p.date.slice(5),x-12,h-12)});ctx.stroke();const t=vals.length>1?vals.at(-1)-vals[0]:0;ctx.fillText(`Trend: ${t>=0?'+':''}${t.toFixed(2)} kg`,50,20)};
async function shared(){if(!new URLSearchParams(location.search).has('shared'))return;try{const db=await new Promise((r,j)=>{const o=indexedDB.open('poodle-share',1);o.onupgradeneeded=()=>o.result.createObjectStore('files');o.onsuccess=()=>r(o.result);o.onerror=j}),tx=db.transaction('files','readwrite'),st=tx.objectStore('files'),file=await new Promise((r,j)=>{const x=st.get('latest');x.onsuccess=()=>r(x.result);x.onerror=j});if(file){await addPhoto(file);st.delete('latest')}history.replaceState({},'',location.pathname)}catch{}}
V.healthRefresh=()=>{injectPredictions();symptoms();photos();vaccineTemplate();V.updateBadge()};V.healthRefresh();shared();
})();