/* v9 extra languages: ES + DE with English fallback */
(() => {
if(typeof texts==='undefined')return;
texts.es={...texts.en,
'nav.home':'Inicio','nav.today':'Hoy','nav.calendar':'Calendario','nav.training':'Entrenamiento','nav.toilet':'Baño','nav.food':'Comida','nav.walk':'Paseo','nav.social':'Socialización','nav.alone':'Solo en casa','nav.grooming':'Peluquería','nav.vet':'Veterinario','nav.journal':'Diario','nav.progress':'Progreso','nav.documents':'Documentos','nav.profile':'Perfil','hero.hello':'Hola,','hero.start':'Empezar el día','stats.skills':'Habilidades','stats.meals':'Comidas','stats.toilet':'Baño','stats.walks':'Paseos','today.title':'Hoy','calendar.title':'Calendario central','training.title':'Entrenamiento y habilidades','training.subtitle':'Cada habilidad tiene su propio progreso.','toilet.title':'Baño','food.title':'Comida y agua','walk.title':'Paseo','social.title':'Socialización','alone.title':'Solo en casa','grooming.title':'Peluquería','vet.title':'Veterinario','journal.title':'Diario','progress.title':'Panel semanal','documents.title':'Documentos','profile.title':'Perfil'};
texts.de={...texts.en,
'nav.home':'Start','nav.today':'Heute','nav.calendar':'Kalender','nav.training':'Training','nav.toilet':'Toilette','nav.food':'Futter','nav.walk':'Spaziergang','nav.social':'Sozialisierung','nav.alone':'Allein zu Hause','nav.grooming':'Pflege','nav.vet':'Tierarzt','nav.journal':'Tagebuch','nav.progress':'Fortschritt','nav.documents':'Dokumente','nav.profile':'Profil','hero.hello':'Hallo,','hero.start':'Tag starten','stats.skills':'Fähigkeiten','stats.meals':'Mahlzeiten','stats.toilet':'Toilette','stats.walks':'Spaziergänge','today.title':'Heute','calendar.title':'Zentraler Kalender','training.title':'Training & Fähigkeiten','training.subtitle':'Jede Fähigkeit hat einen eigenen Fortschritt.','toilet.title':'Toilette','food.title':'Futter & Wasser','walk.title':'Spaziergang','social.title':'Sozialisierung','alone.title':'Allein zu Hause','grooming.title':'Pflege','vet.title':'Tierarzt','journal.title':'Tagebuch','progress.title':'Wochenübersicht','documents.title':'Dokumente','profile.title':'Profil'};
const V=window.PoodleV9,q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function mount(){if(!q('#v9LangMore')){const host=document.createElement('div');host.id='v9LangMore';host.className='theme-grid';host.innerHTML='<button data-more-lang="es">🇪🇸 Español</button><button data-more-lang="de">🇩🇪 Deutsch</button>';q('#v9ThemePanel')?.append(host);qa('[data-more-lang]').forEach(b=>b.onclick=()=>{data.prefs.lang=b.dataset.moreLang;save();try{applyLang()}catch{}V?.refresh?.()})}}
const t=setInterval(()=>{if(q('#v9ThemePanel')){mount();clearInterval(t)}},300);
})();