/* v9 UX: themes, history search, record actions, accessibility, legacy translations, PWA shortcuts */
(() => {
const V=window.PoodleV9,q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];if(!V)return;
function theme(){document.documentElement.dataset.theme=data.prefs.theme||'latte'}
function addThemePanel(){if(q('#v9ThemePanel'))return;const p=document.createElement('article');p.className='panel';p.id='v9ThemePanel';p.innerHTML='<div class="panel-head"><h3>🎨 Theme</h3></div><div class="theme-grid"><button data-theme="latte">☕ Latte</button><button data-theme="rose">🌸 Rose</button><button data-theme="forest">🌿 Forest</button><button data-theme="ocean">🌊 Ocean</button></div>';q('#page-profile')?.append(p);qa('[data-theme]').forEach(b=>b.onclick=()=>{data.prefs.theme=b.dataset.theme;save();theme()})}
function historySearch(page,ids){const p=q(page);if(!p||p.querySelector('.history-search-v9'))return;const b=document.createElement('div');b.className='history-search-v9';b.innerHTML='<input aria-label="Filter history" placeholder="🔎 Search / Caută">';p.querySelector('.section-head')?.after(b);b.querySelector('input').oninput=e=>{const s=e.target.value.toLowerCase();ids.forEach(id=>qa(`#${id} .timeline-item,.${id} .doc-card`).forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(s)))}}
function decorate(){const c=[['mealList','meals',[...data.meals].reverse().slice(0,20)],['toiletList','toilet',[...data.toilet].reverse().slice(0,20)],['walkHistory','walks',[...data.walks].reverse().slice(0,20)],['vaccineList','vaccines',[...data.vaccines].reverse()],['medicineList','medicines',[...data.medicines].reverse()],['vetTimeline','vetVisits',[...data.vetVisits].reverse()],['journalHistory','journal',[...data.journal].reverse().slice(0,14)]];c.forEach(([id,k,a])=>qa(`#${id} .timeline-item`).forEach((r,i)=>{const x=a[i];if(!x||r.dataset.v9)return;r.dataset.v9='1';r.dataset.kind=k;r.dataset.id=x.id;const z=document.createElement('span');z.className='inline-actions';z.innerHTML='<button aria-label="Edit" data-v9-edit>✏️</button><button aria-label="Delete" data-v9-del>🗑️</button>';r.append(z);let start=null;r.addEventListener('pointerdown',e=>start=e.clientX);r.addEventListener('pointerup',e=>{if(start!==null&&e.clientX-start<-90)V.deleteRecord(k,x.id);start=null})}))}
const en={'Salvează':'Save','Anulează':'Cancel','Salvează profilul':'Save profile','Încheie ziua':'Complete day','Mese azi':'Meals today','Hrană':'Food','Apă':'Water','Greutate':'Weight','Pipi azi':'Pee today','Caca azi':'Poop today','Accidente':'Accidents','Ultimul pipi':'Last pee','Jurnal toaletă':'Toilet journal','Istoric plimbări':'Walk history','Rutina de îngrijire':'Care routine','Programări & istoric':'Appointments & history','Medicamente & tratamente':'Medicines & treatments','Istoric veterinar':'Vet history','Ultimele înregistrări':'Latest entries','Vizită':'Visit','Programare':'Appointment','Adaugă rapid':'Quick add','Observații':'Notes','Stare':'Mood','Apetit':'Appetite','Somn (ore)':'Sleep (hours)','Nivel energie':'Energy level'};
function legacy(){if(lang()!=='en')return;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const t=n.nodeValue.trim();if(en[t])n.nodeValue=n.nodeValue.replace(t,en[t])}}
function a11y(){qa('.modal').forEach(m=>{m.setAttribute('role','dialog');m.setAttribute('aria-modal','true')});qa('button').forEach(b=>{if(!b.getAttribute('aria-label')&&!b.textContent.trim())b.setAttribute('aria-label','Action')});qa('canvas').forEach(c=>c.setAttribute('role','img'))}
document.addEventListener('keydown',e=>{if(e.key==='Escape'){qa('.modal.open').forEach(m=>m.classList.remove('open'));q('#onboarding.open')?.classList.remove('open')}if(e.key==='Tab'){const m=q('.modal.open')||q('#onboarding.open');if(!m)return;const f=qa('button,input,select,textarea,a[href],[tabindex]:not([tabindex="-1"])').filter(x=>m.contains(x)&&!x.disabled&&!x.hidden);if(!f.length)return;const first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
document.addEventListener('click',e=>{const ed=e.target.closest('[data-v9-edit]'),del=e.target.closest('[data-v9-del]');if(ed){const r=ed.closest('.timeline-item');V.editRecord(r.dataset.kind,r.dataset.id)}if(del){const r=del.closest('.timeline-item');V.deleteRecord(r.dataset.kind,r.dataset.id)}});
function languages(){if(q('#v9LangExtra'))return;const p=document.createElement('div');p.id='v9LangExtra';p.className='theme-grid';p.innerHTML='<button data-v9-lang="ro">🇷🇴 Română</button><button data-v9-lang="en">🇬🇧 English</button>';q('#v9ThemePanel')?.append(p);qa('[data-v9-lang]').forEach(b=>b.onclick=()=>{data.prefs.lang=b.dataset.v9Lang;save();try{applyLang()}catch{}V.refresh()})}
V.uxRefresh=()=>{theme();addThemePanel();languages();historySearch('#page-journal',['journalHistory']);historySearch('#page-vet',['vaccineList','medicineList','vetTimeline','symptomList']);historySearch('#page-documents',['documentsGrid']);decorate();legacy();a11y();V.updateBadge?.()};
const old=renderAll;renderAll=function(){old();V.uxRefresh?.();V.healthRefresh?.();V.trainingRefresh?.();if(q('#page-data.active'))V.renderData?.()};
const quick=new URLSearchParams(location.search).get('quick');if(quick)setTimeout(()=>{try{addQuick(quick)}catch{}},700);
V.uxRefresh();
})();